### ISSUE TITLE
Doesn't work with latest diffusers

### ISSUE THREAD

**Issue by Trojaner** [sayakpaul/q8-ltx-video#1]
I am trying image to video with latest diffusers and getting this error:
RuntimeError: Promotion for Float8 Types is not supported, attempted to promote Float8_e4m3fn and BFloat16

Same with text to video.

<details>
  <summary>environment</summary>

RTX 4080 16GB
Ubuntu 22.04
torch 2.4.1+cu124
CUDA 12.4
Python 3.10.12

q8_kernels:
```sh
(in venv)
git clone https://github.com/KONAKONA666/q8_kernels
cd q8_kernels
python setup.py install
pip install .
```

diffusers:
```sh
(in venv)
git clone https://github.com/huggingface/diffusers
cd diffusers
wget -O updates.patch https://raw.githubusercontent.com/sayakpaul/q8-ltx-video/main/updates.patch
git apply updates.patch
pip install -e .
```
</details>

<details>
  <summary>inference code</summary>

```py
import gc
import os
from pathlib import Path
import safetensors.torch
import torch
from diffusers import LTXImageToVideoPipeline, LTXPipeline, LTXVideoTransformer3DModel
from diffusers.utils import export_to_video
from huggingface_hub import hf_hub_download
from PIL import Image
from q8_kernels.graph.graph import make_dynamic_graphed_callable
from .q8_ltx import (
    check_transformer_replaced_correctly,
    replace_gelu,
    replace_linear,
    replace_rms_norm,
)

_pipe = None


def image_to_video(
    image: Image.Image,
    prompt: str,
    negative_prompt: str,
    num_inference_steps: int,
    num_frames: int,
    output_file: Path,
    max_sequence_length: int = 512,
):
    assert _pipe is not None, "LTX model not loaded"

    image = image.convert("RGB")
    text_encoding_pipeline = _load_text_encoding_pipeline()

    (
        prompt_embeds,
        prompt_attention_mask,
        negative_prompt_embeds,
        negative_prompt_attention_mask,
    ) = _encode_prompt(
        pipe=text_encoding_pipeline,
        prompt=prompt,
        negative_prompt=negative_prompt,
        max_sequence_length=max_sequence_length,
    )

    del text_encoding_pipeline

    video = _pipe(  # type: ignore
        image=image,
        prompt_embeds=prompt_embeds,
        prompt_attention_mask=prompt_attention_mask,
        negative_prompt_embeds=negative_prompt_embeds,
        negative_prompt_attention_mask=negative_prompt_attention_mask,
        width=image.width,
        height=image.height,
        num_frames=num_frames,
        num_inference_steps=num_inference_steps,
        guidance_scale=3.6,
    ).frames[0]

    export_to_video(video, str(output_file), fps=24)

    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()
    gc.collect()


def load_model():
    global _pipe

    if _pipe is not None:
        return

    transformer = _load_q8_transformer("sayakpaul/q8-ltx-video")
    _pipe = LTXImageToVideoPipeline.from_pretrained(
        "Lightricks/LTX-Video",
        text_encoder=None,
        transformer=None,
    )

    _pipe.transformer = transformer
    _pipe.transformer = _pipe.transformer.to(torch.bfloat16)

    for b in _pipe.transformer.transformer_blocks:
        b.to(dtype=torch.float)

    for n, m in _pipe.transformer.transformer_blocks.named_parameters():
        if "scale_shift_table" in n:
            m.data = m.data.to(torch.bfloat16)

    _pipe.transformer.forward = make_dynamic_graphed_callable(_pipe.transformer.forward)
    _pipe.vae = _pipe.vae.to(torch.bfloat16)

    _pipe = _pipe.to("cuda")


def unload_model():
    global _pipe

    if _pipe is None:
        return

    del _pipe.transformer  # type: ignore
    del _pipe.vae  # type: ignore
    del _pipe.text_encoder  # type: ignore
    _pipe = None

    from modules import models

    models.clear_torch_cache()


def _load_text_encoding_pipeline():
    return LTXPipeline.from_pretrained(
        "Lightricks/LTX-Video", transformer=None, vae=None, torch_dtype=torch.bfloat16
    ).to("cuda")


def _encode_prompt(pipe, prompt, negative_prompt, max_sequence_length=512):
    (
        prompt_embeds,
        prompt_attention_mask,
        negative_prompt_embeds,
        negative_prompt_attention_mask,
    ) = pipe.encode_prompt(
        prompt=prompt,
        negative_prompt=negative_prompt,
        max_sequence_length=max_sequence_length,
    )
    return (
        prompt_embeds,
        prompt_attention_mask,
        negative_prompt_embeds,
        negative_prompt_attention_mask,
    )


def _load_q8_transformer(q8_transformer_path: str):
    with torch.device("meta"):
        transformer_config = LTXVideoTransformer3DModel.load_config(
            "Lightricks/LTX-Video", subfolder="transformer"
        )
        transformer = LTXVideoTransformer3DModel.from_config(transformer_config)  # type: ignore

    transformer = replace_gelu(transformer)[0]
    transformer = replace_linear(transformer)[0]
    transformer = replace_rms_norm(transformer)[0]

    if os.path.isfile(f"{q8_transformer_path}/diffusion_pytorch_model.safetensors"):
        state_dict = safetensors.torch.load_file(
            f"{q8_transformer_path}/diffusion_pytorch_model.safetensors"
        )
    else:
        state_dict = safetensors.torch.load_file(
            hf_hub_download(q8_transformer_path, "diffusion_pytorch_model.safetensors")
        )
    transformer.load_state_dict(state_dict, strict=True, assign=True)
    check_transformer_replaced_correctly(transformer)
    return transformer


if __name__ == "__main__":
    import time
    from datetime import date

    failed = False

    try:
        load_model()

        image = Image.open("image.png")

        prompt = "A woman with long brown hair and light skin smiles at another woman with long blonde hair. The woman with brown hair wears a black jacket and has a small, barely noticeable mole on her right cheek. The camera angle is a close-up, focused on the woman with brown hair's face. The lighting is warm and natural, likely from the setting sun, casting a soft glow on the scene. The scene appears to be real-life footage"
        negative_prompt = "worst quality, inconsistent motion, blurry, jittery, distorted"

        file = (
            f'{date.today().strftime("%Y_%m_%d")}/test_{int(time.time())}'  # noqa: E501
        )
        output_file = Path("outputs") / f"{file}.mp4"
        output_file.parent.mkdir(parents=True, exist_ok=True)

        with torch.no_grad():
            torch.manual_seed(42)

            image_to_video(
                image,
                prompt,
                negative_prompt,
                num_inference_steps=50,
                num_frames=161,
                output_file=output_file,
            )
    except Exception:
        import traceback

        traceback.print_exc()
        failed = True

    if failed:
        exit(1)
```
</details>

<details>
  <summary>logs</summary>

```
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 32.05it/s]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.10it/s]
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.45it/s]
  0%|                                                                                                                                | 0/50 [00:00<?, ?it/s]/home/ml/text-generation-webui/venv/lib/python3.10/site-packages/torch/cuda/graphs.py:83: UserWarning: The CUDA Graph is empty. This usually means that the graph was attempted to be captured on wrong device or stream. (Triggered internally at ../aten/src/ATen/cuda/CUDAGraph.cpp:222.)
  super().capture_end()
  0%|                                                                                                                                | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ml/text-generation-webui/extensions/functions/tools/diffusion/ltx_video_generation.py", line 186, in <module>
    image_to_video(
  File "/home/ml/text-generation-webui/extensions/functions/tools/diffusion/ltx_video_generation.py", line 49, in image_to_video
    video = _pipe(  # type: ignore
  File "/home/ml/text-generation-webui/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ml/diffusers/src/diffusers/pipelines/ltx/pipeline_ltx_image2video.py", line 786, in __call__
    noise_pred = self.transformer(
  File "/home/ml/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ml/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ml/text-generation-webui/venv/lib/python3.10/site-packages/q8_kernels/graph/graph.py", line 199, in dynamic_graphed_callable
    cached_callable = simple_make_graphed_callable(
  File "/home/ml/text-generation-webui/venv/lib/python3.10/site-packages/q8_kernels/graph/graph.py", line 220, in simple_make_graphed_callable
    return make_graphed_callable(func,
  File "/home/ml/text-generation-webui/venv/lib/python3.10/site-packages/q8_kernels/graph/graph.py", line 249, in make_graphed_callable
    func(*tree_copy(example_inputs, detach=True),
  File "/home/ml/diffusers/src/diffusers/models/transformers/transformer_ltx.py", line 441, in forward
    hidden_states = block(
  File "/home/ml/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ml/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ml/diffusers/src/diffusers/models/transformers/transformer_ltx.py", line 264, in forward
    hidden_states = hidden_states + ff_output * gate_mlp
RuntimeError: Promotion for Float8 Types is not supported, attempted to promote Float8_e4m3fn and BFloat16
```
</details>

**Comment by sayakpaul** [comment]
Did you apply the chnages I talked about here? 

<img width="927" alt="Image" src="https://github.com/user-attachments/assets/a61bde07-4337-4d14-b21d-15a4380f2cc3" />

**Comment by Trojaner** [comment]
Yes; I installed diffusers like this:

```sh
git clone https://github.com/huggingface/diffusers
cd diffusers
wget -O updates.patch https://raw.githubusercontent.com/sayakpaul/q8-ltx-video/main/updates.patch
git apply updates.patch
pip install -e .
```

**Comment by sayakpaul** [comment]
Maybe you could clone `diffusers` from the `v0.32.1-release` branch and retry?

**Comment by Trojaner** [comment]
I will try later today and let you know.

**Comment by Trojaner** [comment]
v0.32.1-patch results in the following error:
```
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 15.60it/s]
Traceback (most recent call last):
  File "/home/ml/text-generation-webui/extensions/functions/tools/diffusion/ltx_video_generation.py", line 212, in <module>
    load_model()
  File "/home/ml/text-generation-webui/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ml/text-generation-webui/extensions/functions/tools/diffusion/ltx_video_generation.py", line 152, in load_model
    _pipe = LTXImageToVideoPipeline.from_pretrained(
  File "/home/ml/text-generation-webui/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ml/diffusers/src/diffusers/pipelines/pipeline_utils.py", line 976, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "/home/ml/diffusers/src/diffusers/pipelines/ltx/pipeline_ltx_image2video.py", line 210, in __init__
    self.transformer_spatial_patch_size = self.transformer.config.patch_size if hasattr(self, "transformer") else 1
AttributeError: 'NoneType' object has no attribute 'config'
```

**Comment by Trojaner** [comment]
I fixed it by replacing:

```py
transformer = _load_q8_transformer("sayakpaul/q8-ltx-video")
_pipe = LTXImageToVideoPipeline.from_pretrained(
    "Lightricks/LTX-Video",
    text_encoder=None,
    transformer=None,
).to("cuda")
_pipe.transformer = transformer
```

with

```py
transformer = _load_q8_transformer("sayakpaul/q8-ltx-video")
_pipe = LTXImageToVideoPipeline.from_pretrained(
    "Lightricks/LTX-Video",
    text_encoder=None,
    transformer=transformer,
).to("cuda")
```

It works with 0.32.1 now but the patch fails with latest diffusers

**Comment by sayakpaul** [comment]
Yeah this repo is an experimental project. Perhaps clarifying that from the readme would be helpful?
